[platformio]
data_dir = $PROJECT_DIR/rootfs

[env:featheresp32-s2]
platform = espressif32
board = featheresp32-s2
framework = arduino

lib_deps =
    esp32async/ESPAsyncWebServer@^3.7.7
    ciniml/WireGuard-ESP32@^0.1.5

board_build.filesystem = littlefs